import { DesignState, DesignTheme } from '@/store/designStore';
import { Layout, Part } from '@/types/layout';

interface ExportOptions {
    includeComments?: boolean;
    useTypeScript?: boolean;
    cssFormat?: 'module' | 'styled-components' | 'inline';
}

export interface ReactExportResult {
    component: string;
    styles: string;
    fileName: string;
}

export class ReactExporter {
    /**
     * Export the entire design as a React component
     */
    public static exportToReact(
        design: DesignState,
        layout: Layout | null,
        parts: Part[],
        options: ExportOptions = {}
    ): ReactExportResult {
        const {
            includeComments = true,
            useTypeScript = true,
            cssFormat = 'module'
        } = options;

        const imports = this.generateImports(cssFormat);
        const componentName = this.sanitizeComponentName(design.meta.name);
        const styles = this.generateStylesModule(design.theme, cssFormat);
        const jsx = this.generateJSX(layout, parts, design.theme);

        const fileExtension = useTypeScript ? 'tsx' : 'jsx';
        const typeAnnotation = useTypeScript ? ': React.FC' : '';

        let code = '';

        if (includeComments) {
            code += `/**\n * Generated by DesignLab\n * Design: ${design.meta.name}\n * Author: ${design.meta.author}\n */\n\n`;
        }

        code += imports;
        code += '\n\n';

        if (cssFormat === 'module') {
            code += `import styles from './${componentName}.module.css';\n\n`;
        }

        code += `const ${componentName}${typeAnnotation} = () => {\n`;
        code += `  return (\n`;
        code += this.indent(jsx, 2);
        code += `  );\n`;
        code += `};\n\n`;
        code += `export default ${componentName};\n`;

        return {
            component: code,
            styles: styles,
            fileName: `${componentName}.${fileExtension}`
        };
    }

    /**
     * Generate imports based on CSS format
     */
    private static generateImports(cssFormat: 'module' | 'styled-components' | 'inline'): string {
        let imports = `import React from 'react';\n`;

        if (cssFormat === 'styled-components') {
            imports += `import styled from 'styled-components';\n`;
        }

        return imports;
    }

    /**
     * Generate JSX for the layout and parts
     */
    private static generateJSX(layout: Layout | null, parts: Part[], theme: DesignTheme): string {
        if (!layout) {
            return `<div>No layout defined</div>`;
        }

        const containerStyle = {
            display: 'grid',
            gridTemplateColumns: layout.gridTemplateColumns,
            gridTemplateRows: layout.gridTemplateRows,
            gridTemplateAreas: layout.gridTemplateAreas.map(a => `"${a.replace(/"/g, '')}"`).join(' '),
            gap: layout.gap,
            backgroundColor: theme.colors.background,
            color: theme.colors.text,
            minHeight: '100vh'
        };

        let jsx = `<div style={${JSON.stringify(containerStyle, null, 2)}}>\n`;

        for (const area of layout.areas) {
            const areaParts = parts.filter(p => p.areaId === area.id);

            jsx += `  <div style={{ gridArea: '${area.gridArea}' }}>\n`;

            for (const part of areaParts) {
                jsx += `    ${this.generatePartJSX(part, theme)}\n`;
            }

            jsx += `  </div>\n`;
        }

        jsx += `</div>`;

        return jsx;
    }

    /**
     * Generate JSX for a single part
     */
    private static generatePartJSX(part: Part, theme: DesignTheme): string {
        const props = part.props || {};

        switch (part.type) {
            case 'button':
                return `<button style={{ 
                    padding: '${props.size === 'lg' ? '12px 24px' : '8px 16px'}',
                    backgroundColor: '${theme.colors.primary}',
                    color: '#ffffff',
                    border: 'none',
                    borderRadius: '${theme.radius}',
                    cursor: 'pointer'
                }}>${props.text || 'Button'}</button>`;

            case 'heading':
                const level = props.level || 2;
                return `<h${level} style={{ 
                    fontFamily: '${theme.fontHeading}',
                    color: '${theme.colors.text}'
                }}>${props.text || 'Heading'}</h${level}>`;

            case 'text':
                return `<p style={{ 
                    fontSize: '${props.size || '16px'}',
                    fontFamily: '${theme.fontBody}',
                    color: '${theme.colors.text}'
                }}>${props.text || 'Text'}</p>`;

            case 'image':
                return `<img 
                    src="${props.src || 'https://placehold.co/600x400'}" 
                    alt="${props.alt || 'Image'}" 
                    style={{ 
                        width: '100%',
                        aspectRatio: '${props.aspectRatio || '16/9'}',
                        objectFit: '${props.fit || 'cover'}',
                        borderRadius: '${theme.radius}'
                    }} 
                />`;

            default:
                return `<div>/* ${part.type} component */</div>`;
        }
    }

    /**
     * Generate CSS module or styled-components
     */
    private static generateStylesModule(theme: DesignTheme, format: 'module' | 'styled-components' | 'inline'): string {
        if (format === 'inline') {
            return ''; // Styles are inline
        }

        if (format === 'module') {
            return `/* Generated styles */
.container {
  background-color: ${theme.colors.background};
  color: ${theme.colors.text};
  font-family: ${theme.fontBody};
}

.button {
  background-color: ${theme.colors.primary};
  color: #ffffff;
  border: none;
  border-radius: ${theme.radius};
  padding: 8px 16px;
  cursor: pointer;
  font-family: ${theme.fontBody};
}

.button:hover {
  opacity: 0.9;
}

.heading {
  font-family: ${theme.fontHeading};
  color: ${theme.colors.text};
}
`;
        }

        // styled-components format
        return `import styled from 'styled-components';

export const Container = styled.div\`
  background-color: ${theme.colors.background};
  color: ${theme.colors.text};
  font-family: ${theme.fontBody};
\`;

export const Button = styled.button\`
  background-color: ${theme.colors.primary};
  color: #ffffff;
  border: none;
  border-radius: ${theme.radius};
  padding: 8px 16px;
  cursor: pointer;
  font-family: ${theme.fontBody};

  &:hover {
    opacity: 0.9;
  }
\`;
`;
    }

    /**
     * Sanitize component name
     */
    private static sanitizeComponentName(name: string): string {
        return name
            .replace(/[^a-zA-Z0-9]/g, '')
            .replace(/^[0-9]/, 'Component$&')
            || 'GeneratedComponent';
    }

    /**
     * Indent code
     */
    private static indent(code: string, spaces: number): string {
        const indentation = ' '.repeat(spaces);
        return code.split('\n').map(line => indentation + line).join('\n');
    }
}
